version: "0.0.4"

display:
    command_line: "user@chatimus ~$ "

watchpeoplecode:
    channel: ""
    connect: false

    display_settings:
        display_missing: true

twitch:
    # in the format `oauth:asdasd234asd234ad234asds23`
    oauth_token: ""
    channel: ""
    nick: ""
    connect: false

    display_settings:
        display_missing: true

livecoding:
    # this MUST be your livecode name
    name: ""
    # this can be your profile password
    password: ""
    bot_nick: ""
    room: ""
    connect: true

    display_settings:
        display_missing: true

youtube:
     # NOTE: only pass in channel id if you want to connect chat to your 
     # permenant landing page
    channel_id: ""
    youtube_url: ""
    connect: false

    display_settings:
        display_missing: true
