version: "0.1.1"

display:
    command_line: "user@chatimus ~$ "

services:

    irc:

        twitch:
            # I use this site to get oauth_token 
            # https://twitchapps.com/tmi/
            # use this format: `oauth:asdasd234asd234ad234asds23`
            password: ""
            # this will be your twitch channel
            # should be something like "#beohoff"
            channel: ""
            # I believe this has to be your twitch acct name
            nick: ""
            host: 'irc.twitch.tv'
            socket_address: ""
            connect: false
            display_missing: true

    xmpp:

        livecoding:
            # this MUST be your livecode name
            # This is a name
            local: ""
            # this can be your profile password
            password: ""
            bot_nick: ""
            # room is going to look something like `benhoff@chat.livecoding.tv`
            room: ""
            domain: 'livecoding.tv'
            resource: 'CHATIMUSMAXIMUS'
            socket_address: ""
            connect: false
            display_missing: true

    # socket_io is hardcoded for watchpeople code
    # feel free to yell at me about that on github
    socket_io:

        watchpeoplecode:
            streamer_name: ""
            namespace: '/chat'
            website_url: 'http://www.watchpeoplecode.com/socket.io/1/'
            socket_address: ""
            connect: false 
            display_missing: true
    
    # youtube is special.
    youtube:
        socket_address: ""
        connect: false
        display_missing: true
        
        # must install selenium. Don't need OAuth credentials
        javascript_scraper:
            youtube_url: ""
        
        # go to goole developers console. Create an app and request
        # YouTube Data API v3 access. Create and download OAuth credentials
        # and put the filepath info in `client_secrets_file`
        api_connect:
            # use an absolute filepath!
            client_secrets_file: ""
